function agentTrace = importLogfile(filename)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   AGENTTRACE = IMPORTFILE(FILENAME) Reads data from text file FILENAME
%   for the default selection.
%
%   AGENTTRACE = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from
%   rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   agentTrace = importfile('agentTrace.txt', 1, 1);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2016/08/25 16:12:20

%% Initialize variables.

delimiter = {',',' '};

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%   column4: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'EmptyValue' ,NaN, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
dataArray([1, 2, 3, 4]) = cellfun(@(x) num2cell(x), dataArray([1, 2, 3, 4]), 'UniformOutput', false);
agentTrace = [dataArray{1:end}];